theme: jekyll-theme-minimal

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
highlighter: rouge
plugins_dir: _plugins
baseurl: /pages

title: "pages"
description: "How to generate pages with rouge support"
logo: "/assets/logo.png"   # optional
show_downloads: true       # controls the download links in header
github:
  is_user_page: true
  owner_url: "https://github.com/miyako"
  repository_url: "https://github.com/miyako/pages"
  is_project_page: false
