theme: jekyll-theme-minimal

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
highlighter: rouge
plugins_dir: _plugins
exclude:
  - LICENSE
  - README.md
  - resources/
title: "The title of your site"
description: "A short description of your site's purpose"
